create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 email text, role text not null default 'user' check (role in ('user','admin')),
 created_at timestamptz not null default now()
);
create table if not exists public.items (
 id bigint generated by default as identity primary key,
 name text not null, description text default '',
 created_by uuid not null references auth.users(id) on delete cascade,
 status text not null default 'pending' check (status in ('pending','approved','rejected')),
 approved_by uuid references auth.users(id) on delete set null,
 approved_at timestamptz, created_at timestamptz not null default now()
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,email) values(new.id,new.email) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.set_item_approved_at() returns trigger language plpgsql as $$
begin
 if new.status='approved' and old.status is distinct from 'approved' then new.approved_at=now();
 elsif new.status<>'approved' then new.approved_at=null; end if;
 return new;
end; $$;
drop trigger if exists items_approved_at on public.items;
create trigger items_approved_at before update on public.items for each row execute procedure public.set_item_approved_at();
alter table public.profiles enable row level security;
alter table public.items enable row level security;

-- Setelah register akun admin melalui aplikasi, jalankan:
-- update public.profiles set role='admin' where email='admin@example.com';
-- Jangan pernah menjadikan form register publik sebagai pembuat admin.
