-- Jalankan script ini di Supabase SQL Editor.

create table if not exists public.items (
    id bigint generated by default as identity primary key,
    name text not null,
    description text default '',
    created_at timestamptz not null default now()
);

-- Untuk contoh CRUD sederhana ini, aplikasi menggunakan service/API key
-- yang sesuai dengan konfigurasi server. Jika menggunakan anon key,
-- atur RLS/policies sesuai kebutuhan aplikasi Anda.
--
-- Contoh policy untuk akses anon (OPSIONAL, jangan gunakan untuk data sensitif):
alter table public.items enable row level security;

create policy "Allow public read"
on public.items
for select
to anon
using (true);

create policy "Allow public insert"
on public.items
for insert
to anon
with check (true);

create policy "Allow public update"
on public.items
for update
to anon
using (true)
with check (true);

create policy "Allow public delete"
on public.items
for delete
to anon
using (true);
