create table if not exists public.connection_test (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

insert into public.connection_test default values;

-- Jika memakai service role key untuk testing server-side,
-- RLS tidak menghalangi query service role.
